site_name: will-docs

repo_url: https://github.com/WilliamYizima/williamyizima.github.io

theme:
    name: cyborg
    nav_style: dark

nav:
    - Home: index.md
    - Exemplo01:
        - Básico: 01-ia/index.md
    - Utils:
        - Web: 02-Utils/01-web.md
    - Sobre Mim: xx-about/index.md

extra_css:
    - css/extra_css.css

extra_js:
    - css/extra_js.js